<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="14426" started-at="2020-08-09T12:33:49 EDT" finished-at="2020-08-09T12:34:04 EDT">
    <groups>
    </groups>
    <test name="Default test" duration-ms="14426" started-at="2020-08-09T12:33:49 EDT" finished-at="2020-08-09T12:34:04 EDT">
      <class name="com.qa.darksky.tests.TodayPageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.darksky.tests.TodayPageTest@614ddd49]" name="setUp" is-config="true" duration-ms="10415" started-at="2020-08-09T12:33:49 EDT" finished-at="2020-08-09T12:34:00 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="clickTodayTest()[pri:1, instance:com.qa.darksky.tests.TodayPageTest@614ddd49]" name="clickTodayTest" duration-ms="3112" started-at="2020-08-09T12:34:00 EDT" finished-at="2020-08-09T12:34:03 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clickTodayTest -->
        <test-method status="FAIL" signature="verifyLowTempTest()[pri:2, instance:com.qa.darksky.tests.TodayPageTest@614ddd49]" name="verifyLowTempTest" duration-ms="369" started-at="2020-08-09T12:34:03 EDT" finished-at="2020-08-09T12:34:03 EDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [76] but found [72]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [76] but found [72]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at com.qa.darksky.utils.ElementUtil.getVerifyLowest(ElementUtil.java:158)
at com.qa.darksky.pages.TodayPage.verifyLowTemp(TodayPage.java:52)
at com.qa.darksky.tests.TodayPageTest.verifyLowTempTest(TodayPageTest.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLowTempTest -->
        <test-method status="FAIL" signature="verifyHighTempTest()[pri:3, instance:com.qa.darksky.tests.TodayPageTest@614ddd49]" name="verifyHighTempTest" duration-ms="269" started-at="2020-08-09T12:34:03 EDT" finished-at="2020-08-09T12:34:04 EDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [85] but found [87]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [85] but found [87]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at com.qa.darksky.utils.ElementUtil.getVerifyHighest(ElementUtil.java:179)
at com.qa.darksky.pages.TodayPage.verifyHighTemp(TodayPage.java:56)
at com.qa.darksky.tests.TodayPageTest.verifyHighTempTest(TodayPageTest.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyHighTempTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.darksky.tests.TodayPageTest@614ddd49]" name="tearDown" is-config="true" duration-ms="207" started-at="2020-08-09T12:34:04 EDT" finished-at="2020-08-09T12:34:04 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.darksky.tests.TodayPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
